spring.application.name=backend
server.port=8080

# Database Configuration (H2)
spring.datasource.url=jdbc:h2:file:./data/expense_tracker;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# JWT Configurations
# 256-bit secret key for HMAC-SHA256
app.jwt.secret=9a6747fc6259ac37d45a9526ff9d93b3c434914101e4a362bfcf1bf2d4c0628e9a6747fc6259ac37d45a9526ff9d93b3
app.jwt.expiration-ms=86400000
